[build]
builder = "nixpacks"
buildCommand = "yarn install"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3